#!/bin/sh
# Dated snapshot of the Docker lab (WSL): containers, images, network, runner contents.
# Starts nothing, changes nothing. Usage:  sh lab/snapshot.sh > lab/SNAPSHOT.md
set -e
echo "# Lab snapshot — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo
echo "Generated by \`lab/snapshot.sh\` (docker inspect, docker images, docker exec). Read-only."
echo
echo "## Notes"
echo
echo "- KICKS: installation in \`Guide_installation_KICKS_1.5.0_TK5_OculiX.pdf\` (French), day-to-day use in \`KICKS.md\`."
echo "- Public KICKS image: \`ghcr.io/julienmerconsulting/target-mainframe-kicks:1.5.0-installed\` (MYLOGON included since 2026-09-14); the compose pulls it."
echo "- Local safety nets: \`oculix-lab/target-mainframe-kicks:kicks-installed-2026-08-27\` (before MYLOGON) and \`...:kicks-installed-2026-09-14\`."
echo
echo "## Images"
echo
echo "| Image | ID | Size | Created |"
echo "|---|---|---|---|"
docker images --format "| {{.Repository}}:{{.Tag}} | {{.ID}} | {{.Size}} | {{.CreatedAt}} |" | grep -E "mainframe|runner|oculix-lab"
echo
echo "## Containers"
echo
for c in target-mainframe target-mainframe-kicks oculix-runner; do
  docker inspect "$c" > /dev/null 2>&1 || { echo "### $c: absent"; echo; continue; }
  echo "### $c"
  echo
  docker inspect "$c" --format '- image: `{{.Config.Image}}`
- created: {{.Created}}
- state: {{.State.Status}} (exit {{.State.ExitCode}})
- restart: {{.HostConfig.RestartPolicy.Name}} · memory: {{.HostConfig.Memory}} · nano-cpus: {{.HostConfig.NanoCpus}}
- ports: {{range $k, $v := .HostConfig.PortBindings}}{{$k}}→{{range $v}}{{.HostPort}}{{end}} {{end}}
- entrypoint: `{{.Config.Entrypoint}}`
- networks: {{range $k, $v := .NetworkSettings.Networks}}{{$k}} {{end}}
- mounts: {{len .Mounts}}'
  echo "- env:"
  docker inspect "$c" --format '{{range .Config.Env}}{{printf "  - `%s`\n" .}}{{end}}' | grep -v 'PATH='
  echo
done
echo "## Network"
echo
docker network inspect oculix-mainframe-lab_lab-net --format '- `{{.Name}}` · driver {{.Driver}} · {{range .IPAM.Config}}{{.Subnet}}{{end}}' 2>/dev/null || echo "- lab-net network absent"
echo
echo "## Inside the runner"
echo
if docker exec oculix-runner true 2>/dev/null; then
  echo '```'
  docker exec oculix-runner sh -c 'java -version 2>&1 | head -1; echo; sha256sum /opt/oculix/*.jar; echo; dpkg -l xvfb xauth libxtst6 libxi6 2>/dev/null | grep ^ii | awk "{print \$2, \$3}"'
  echo '```'
else
  echo "- oculix-runner stopped, contents not read"
fi
